- hosts: localhost
  user: root
  vars:
  roles:
  - role: acm-deployment-defaults

  - role: osp-set-project

  - role: acm-gather-deployment-facts

  - role: osp-inventory-security-groups

  - role: osp-security-groups

  - role: git-pull-post-install

  - role: ocp-infra-machinesets

  - role: ocp-generate-api-server-config

  - role: ocp-certificate-inject

  - role: acm-add-cluster-policy

  - role: git-push-post-install
