---
# tasks file for acm-gather-deployment-facts

- name: Validate presence of CA Certificate
  stat: path="{{ cacert }}"
  register: cacert_status

- name: Fail if the CA Certificate is not present
  fail: msg="The CA Certificate {{ cacert }} is not present.  This is required for OpenStack SDK Communications."
  when: not cacert_status.stat.exists


- import_tasks: osp-set-project.yaml

