
- name: Add Openstack service account "{{ osp_username }}" and grant appropriate privilages
  os_user_role:
    auth:
      auth_url: "{{ osp_url }}"
      username: "{{ osp_admin }}"
      password: "{{ osp_adminkey }}"
      user_domain_name: "{{ osp_admindomain }}"
      project_name: "admin"
      project_domain_name: "default"
    user: "{{ osp_username }}"
    domain: "{{ osp_userdomain }}"
    project: "{{ osp_project }}"
    role: "{{ item }}"
    cacert: "{{ cacert }}"
  with_items:
    - member
    - admin
